---
- name: Make sure the whatsupdocker container is created and running
  community.general.docker_container:
    name: "whatsupdocker"
    image: "getwud/wud:{{ whatsupdocker_version }}"
    pull: "always"
    recreate: "{{ force_recreate | default(false) }}"
    state: started
    restart_policy: unless-stopped
    security_opts:
      - no-new-privileges:true
      - apparmor:docker-default
    networks:
      - name: homepage_network
      - name: docker_proxy_network
      - name: reverse_proxy_network
      - name: bridge
    env:
      DOCKER_HOST: tcp://docker_proxy:2375
      WUD_TRIGGER_SMTP_GMAIL_HOST: "{{ email_smtp_host }}"
      WUD_TRIGGER_SMTP_GMAIL_PORT: "{{ email_smtp_port }}"
      WUD_TRIGGER_SMTP_GMAIL_USER: "{{ email_login }}"
      WUD_TRIGGER_SMTP_GMAIL_PASS: "{{ email_password }}"
      WUD_TRIGGER_SMTP_GMAIL_FROM: "{{ email_login }}"
      WUD_TRIGGER_SMTP_GMAIL_TO: "{{ email_recipient }}"
      WUD_TRIGGER_SMTP_GMAIL_TLS_ENABLED: "false"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "reverse_proxy_network"
      traefik.http.routers.whatsupdocker.entrypoints: "https"
      traefik.http.routers.whatsupdocker.rule: "Host(`{{ whatsupdocker_host }}`)"
      traefik.http.routers.whatsupdocker.tls: "true"
      traefik.http.routers.whatsupdocker.service: "whatsupdocker"
      traefik.http.routers.whatsupdocker.middlewares: "secure-vpn-with-auth@file"
      traefik.http.services.whatsupdocker.loadbalancer.server.port: "3000"
