global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "traefik"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["traefik:8899"]
  - job_name: "crowdsec"
    static_configs:
      - targets: ["crowdsec:6060"]
  # - job_name: "wg-easy"
  #   scrape_interval: 30s
  #   metrics_path: /metrics/prometheus
  #   static_configs:
  #     - targets: ["wg-easy:8899"]
  #   authorization:
  #     type: Bearer
  #     credentials: "{{ wireguard_password }}"
